In [50]:
import numpy as np
import matplotlib.pyplot as plt
import astropy.io.fits as pyfits
import pylab as p
from astropy import units as u
from astropy.coordinates import SkyCoord
import astropy.io.ascii as easy
import astropy as astro

#import dist as DL
%pylab inline
%matplotlib inline

Populating the interactive namespace from numpy and matplotlib


In [54]:
ff = open('Karta.txt', 'r')
LIR=[]
RADEC=[]
z=[]
for line in ff:
    line = line.strip()
    columns = line.split()
    LIR.append(float(columns[3]))
    RADEC.append(columns[2])
    z.append(float(columns[5]))



    


['J100046.073+013439.89', 'J100034.222+013543.18', 'J100133.372+013547.59', 'J100041.554+013552.68', 'J100036.456+013549.15', 'J100241.784+013550.07', 'J100118.446+013604.98', 'J100048.497+013607.34', 'J100116.582+013609.14', 'J100109.590+013629.33', 'J100129.422+013633.76', 'J095805.784+013622.56', 'J100252.781+013642.26', 'J100231.814+013642.98', 'J100117.350+013638.62', 'J100033.430+013629.76', 'J095839.065+013634.19', 'J095804.610+013635.63', 'J100041.566+013658.72', 'J095843.920+013653.86', 'J100147.563+013647.58', 'J095919.747+013657.92', 'J095903.677+013701.25', 'J100244.503+013657.84', 'J100211.275+013706.54', 'J100154.310+013703.62', 'J095852.080+013712.94', 'J100108.825+013717.15', 'J095816.625+013719.37', 'J100236.787+013731.30', 'J100037.186+013734.41', 'J095909.878+013747.77', 'J095830.278+013729.67', 'J100127.120+013745.60', 'J100238.251+013746.72', 'J100035.419+013756.07', 'J100014.472+013757.73', 'J095957.127+013741.54', 'J095845.019+013759.17', 'J100124.401+013804.38',

In [63]:
RAd=[]
DECd=[]
for item in RADEC:
    RAd.append(item[1:3]+'h'+item[3:5]+'m'+item[5:11]+'s')
    DECd.append(item[11:14]+'d'+a[14:16]+'m'+a[16:21]+'s')
coords=SkyCoord(ra=RAd,dec=DECd)
print np.size(coords)
coords.ra.deg

1503


array([ 150.19197083,  150.14259167,  150.38905   , ...,  150.06855   ,
        150.10697083,  150.38255833])

In [65]:
for item in coords:
    print item.ra.deg

150.191970833
150.142591667
150.38905
150.173141667
150.1519
150.6741
150.326858333
150.202070833
150.319091667
150.289958333
150.372591667
149.5241
150.719920833
150.632558333
150.322291667
150.139291667
149.662770833
149.519208333
150.173191667
149.683
150.448179167
149.832279167
149.765320833
150.685429167
150.546979167
150.476291667
149.717
150.286770833
149.569270833
150.653279167
150.154941667
149.791158333
149.626158333
150.363
150.659379167
150.147579167
150.0603
149.988029167
149.687579167
150.351670833
149.767770833
149.54015
150.139541667
150.698779167
150.3316
149.807941667
149.96895
150.709841667
150.188729167
150.18855
149.882391667
150.703641667
149.947879167
150.654620833
150.0921
150.084958333
149.923541667
149.738679167
150.012
150.6353
150.099508333
150.319779167
150.228670833
150.329608333
150.173841667
150.03125
150.028258333
149.761570833
150.685379167
150.305670833
149.910741667
149.81315
150.717679167
150.587391667
149.979141667
149.943908333
149.992170833
150.2

In [53]:
a='J100119.584+013833.95'
ra1=a[1:3]+'h'+a[3:5]+'m'+a[5:11]+'s'
dec1=a[11:14]+'d'+a[14:16]+'m'+a[16:21]+'s'
pair=SkyCoord(ra=ra1,dec=dec1)
print pair

<SkyCoord (ICRS): (ra, dec) in deg
    (150.3316, 1.64276389)>


In [2]:
for i in range(len(LIR)):
    if LIR[i]>11.6 and z[i]<0.5:
        print z[i],LIR[i],RADEC[i]

<type 'function'>


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[14, 15],
       [20, 21]])